appventas/Models/Calculadora.cs
using System;

namespace appventas.Models
{
    public class Calculadora
    {
        public Double Operador1{get; set;} 
       public Double Operador2 {get; set;}
        public String Operando {get; set;}


    }
}

appventas/Models/Contacto.cs
using System;

namespace appventas.Models
{
    public class Contacto
    {
        public String FirstName{get; set;}
          public String LastName{get; set;}
        public String Email{get; set;}
        public String Phone{get; set;}

        public String Status{get; set;}

    }
}

appventas/Models/ErrorViewModel.cs
using System;

namespace appventas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

appventas/Controllers/CalculadoraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using appventas.Models;

namespace appventas.Controllers
{
    public class CalculadoraController : Controller
    {
        private readonly ILogger<CalculadoraController> _logger;

        public CalculadoraController(ILogger<CalculadoraController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
         ViewData["Message"] = "";
            return View();
        }

        [HttpPost]
        public IActionResult MiMetodoExecute(Calculadora objCalculadora)


        {
            Double result = 0.0 ;
            String message="";
            if("+" == objCalculadora.Operando){
              result =  objCalculadora.Operador1 + objCalculadora.Operador2;
              message = "El resultado es "+ result;
            }
            if("/" == objCalculadora.Operando){
               if(objCalculadora.Operador2 == 0){
              message = "El numero no puede ser dividido entre 0";
               }

                else {
              result =  objCalculadora.Operador1 / objCalculadora.Operador2;
                            message = "El resultado es "+ result;


            }
            }
            ViewData["Message"] = message;
            return View("Index");
        }

       
    }
}

appventas/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using appventas.Models;

namespace appventas.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }


        public IActionResult Index()
        {
            var listcontactos = new List<Contacto>();
            listcontactos.Add(new Contacto(){FirstName="Cristhian", LastName="Cruz", Email="cristhian_cruz@usmp.pe"});
            listcontactos.Add(new Contacto(){FirstName="Nestor", LastName="Cruz", Email="nestor_cruz@usmp.pe"});
            listcontactos.Add(new Contacto(){FirstName="George", LastName="Reyes", Email="iker_cruz@usmp.pe"});

         ViewData["Message"] = "";
            return View(listcontactos);
        }

        [HttpPost]
        public IActionResult Create(Contacto objContacto)


        {
            objContacto.Status = "Registrado";
            ViewData["Message"] = "El contacto ya está "+ objContacto.Status;
            return View("Index");
        }

       
    }
}

appventas/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using appventas.Models;

namespace appventas.Controllers
{
    public class ContactoController : Controller
    {
        private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
         ViewData["Message"] = "";
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contacto objContacto)


        {
            objContacto.Status = "Registrado";
            ViewData["Message"] = "El contacto ya está "+ objContacto.Status;
            return View("Index");
        }

       
    }
}

appventas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using appventas.Models;

namespace appventas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

appventas/Views/Calculadora/Index.cshtml
@model Calculadora
<form asp-controller="Calculadora" asp-action="MiMetodoExecute">
    
    <label asp-for="Operador1" class="control-label"> </label>
    <input asp-for="Operador1" class="form-control"/>

   
    <label asp-for="Operador2" class="control-label"> </label>
    <input asp-for="Operador2" class="form-control"/>

    <div class="form-group"> 
        <label asp-for="Operando" class="control-label"> </label>

        <select asp-for="Operando" >
            <option value="+">suma</option>
            <option value="/">Division</option>

        </select>
    </div>

   
    <div class="form-group">
<button type="submit" class="btn btn-primary">Calcular</button>

    </div>
</form>
<h1>@ViewData["Message"]</h1>

appventas/Views/Contacto/Create.cshtml
@model Contacto
<form asp-controller="Contacto" asp-action="create">
    <label asp-for="FirstName" class="control-label"> </label>
    <input asp-for="FirstName" class="form-control"/>

    <label asp-for="LastName" class="control-label"> </label>
    <input asp-for="LastName" class="form-control"/>

    <label asp-for="Email" class="control-label"> </label>
    <input asp-for="Email" class="form-control"/>

    <label asp-for="Phone" class="control-label"> </label>
    <input asp-for="Phone" class="form-control"/>

   
    <div class="form-group">
<button type="submit" class="btn btn-primary">Registrar</button>

    </div>
</form>
<h1>@ViewData["Message"]</h1>

appventas/Views/Contacto/Index.cshtml
@model Contacto
<form asp-controller="Contacto" asp-action="create">
    <label asp-for="FirstName" class="control-label"> </label>
    <input asp-for="FirstName" class="form-control"/>

    <label asp-for="LastName" class="control-label"> </label>
    <input asp-for="LastName" class="form-control"/>

    <label asp-for="Email" class="control-label"> </label>
    <input asp-for="Email" class="form-control"/>

    <label asp-for="Phone" class="control-label"> </label>
    <input asp-for="Phone" class="form-control"/>

   
    <div class="form-group">
<button type="submit" class="btn btn-primary">Registrar</button>

    </div>
</form>
<h1>@ViewData["Message"]</h1>

appventas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

appventas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - appventas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">appventas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - appventas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>